services:
  - type: web
    name: silvercoin-backend
    env: python
    plan: free
    buildCommand: bash start.sh
    startCommand: bash start.sh
    envVars:
      - key: PORT
        value: "10000"
