services:
  - type: web
    name: silvercoin-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python backend.py"
    envVars:
      - key: PORT
        value: "10000"
